// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA14frTbeF5P2nE_LbbU2oYuQH9L5Txcz4',
    appId: '1:635747715160:web:5ebb4376b6294d9be8622d',
    messagingSenderId: '635747715160',
    projectId: 'workforce-ef2dc',
    authDomain: 'workforce-ef2dc.firebaseapp.com',
    storageBucket: 'workforce-ef2dc.firebasestorage.app',
    measurementId: 'G-C115X8PVEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnOTZSlYbdQ0YbpSjyq0Z_F0Xczvnq8d8',
    appId: '1:635747715160:android:3ada61239fe9b7c8e8622d',
    messagingSenderId: '635747715160',
    projectId: 'workforce-ef2dc',
    storageBucket: 'workforce-ef2dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByPkQburLJlSCX08OXTrd2v9QAMwjp_pw',
    appId: '1:635747715160:ios:9c0ffad5f8983200e8622d',
    messagingSenderId: '635747715160',
    projectId: 'workforce-ef2dc',
    storageBucket: 'workforce-ef2dc.firebasestorage.app',
    iosBundleId: 'com.anb.workforce',
  );
}
